# @name GET
GET http://127.0.0.1:9000/

###

# @name POST
POST http://127.0.0.1:9000/pacientes
Content-Type: application/json

{
    "name": "Ana Paula da Silva",
    "dateBirth": "1961-08-22",
    "genre": "female",
    "cpf": "12345608890",
    "cellphone": 1199287633,
    "address": "Rua Ariston Leda"
}